[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = { type = "dynamic" }
GEMINI_API_KEY = { type = "reference", value = "GEMINI_API_KEY" }
MAIN_API_URL = { type = "reference", value = "MAIN_API_URL" }